services:

  web:
    image: miapp-django
    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    image: miapp-nginx
    depends_on:
      - web
    ports:
      - "80:80"
