# Generated by Django 5.2.3 on 2025-06-11 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Volkswagen', 'Volkswagen'), ('Honda', 'Honda'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Fiat', 'Fiat'), ('Skoda', 'Skoda'), ('SEAT', 'SEAT'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Mitsubishi', 'Mitsubishi'), ('Tesla', 'Tesla'), ('Volvo', 'Volvo'), ('Jeep', 'Jeep'), ('Dodge', 'Dodge'), ('Ram', 'Ram'), ('Chrysler', 'Chrysler'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Lincoln', 'Lincoln'), ('GMC', 'GMC'), ('Land Rover', 'Land Rover'), ('Jaguar', 'Jaguar'), ('Alfa Romeo', 'Alfa Romeo'), ('Maserati', 'Maserati'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Porsche', 'Porsche'), ('Aston Martin', 'Aston Martin'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('Bugatti', 'Bugatti'), ('McLaren', 'McLaren'), ('Lotus', 'Lotus'), ('Mini', 'Mini'), ('Smart', 'Smart'), ('Citroën', 'Citroën'), ('DS Automobiles', 'DS Automobiles'), ('Genesis', 'Genesis'), ('Infiniti', 'Infiniti'), ('Acura', 'Acura'), ('Daihatsu', 'Daihatsu'), ('Proton', 'Proton'), ('Perodua', 'Perodua'), ('Geely', 'Geely'), ('Chery', 'Chery'), ('BYD', 'BYD'), ('NIO', 'NIO'), ('Xpeng', 'Xpeng'), ('Li Auto', 'Li Auto'), ('Great Wall Motors', 'Great Wall Motors'), ('Haval', 'Haval'), ('BAIC', 'BAIC'), ('FAW', 'FAW'), ('Hongqi', 'Hongqi'), ('Roewe', 'Roewe'), ('MG (Morris Garages)', 'MG (Morris Garages)'), ('Lancia', 'Lancia'), ('Dacia', 'Dacia'), ('Tata Motors', 'Tata Motors'), ('Mahindra', 'Mahindra'), ('Maruti Suzuki', 'Maruti Suzuki'), ('Scion', 'Scion'), ('Pontiac', 'Pontiac'), ('Saturn', 'Saturn'), ('Hummer', 'Hummer'), ('Daewoo', 'Daewoo'), ('Oldsmobile', 'Oldsmobile'), ('Isuzu', 'Isuzu'), ('Suzuki', 'Suzuki'), ('Yugo', 'Yugo'), ('Zastava', 'Zastava'), ('Koenigsegg', 'Koenigsegg'), ('Rimac', 'Rimac'), ('Fisker', 'Fisker'), ('Lucid Motors', 'Lucid Motors'), ('Polestar', 'Polestar'), ('Rivian', 'Rivian'), ('Ariel', 'Ariel'), ('Pagani', 'Pagani'), ('Spyker', 'Spyker'), ('Noble', 'Noble'), ('De Tomaso', 'De Tomaso'), ('Saleen', 'Saleen'), ('Pininfarina', 'Pininfarina'), ('SSC North America', 'SSC North America'), ('Gumpert', 'Gumpert'), ('Aptera', 'Aptera'), ('Bollinger Motors', 'Bollinger Motors'), ('Canoo', 'Canoo'), ('VinFast', 'VinFast'), ('Zenos', 'Zenos'), ('Faraday Future', 'Faraday Future'), ('Rezvani', 'Rezvani'), ('W Motors', 'W Motors'), ('TVR', 'TVR'), ('Brilliance Auto', 'Brilliance Auto'), ('Luxgen', 'Luxgen'), ('Togg', 'Togg'), ('Donkervoort', 'Donkervoort'), ('Hispano Suiza', 'Hispano Suiza'), ('Ginetta', 'Ginetta')], max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('motor', models.CharField(max_length=100)),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel')], max_length=10)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coches',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('averia', 'Avería'), ('consumo', 'Consumo')], max_length=20)),
                ('kilometraje', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('detalles', models.TextField()),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datos',
            },
        ),
    ]
